// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1bPxT-A_y9c8UWEUeM2_3KpC5oB_yccY',
    appId: '1:324268770895:web:bb26a0b3b89e3d26ddcc3a',
    messagingSenderId: '324268770895',
    projectId: 'learning-67401',
    authDomain: 'learning-67401.firebaseapp.com',
    storageBucket: 'learning-67401.firebasestorage.app',
    measurementId: 'G-RTJXFHQMY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiRNhMFUu4uSC6DJvbjuQD9lllsOoMIEo',
    appId: '1:324268770895:android:df239554f1747c95ddcc3a',
    messagingSenderId: '324268770895',
    projectId: 'learning-67401',
    storageBucket: 'learning-67401.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmnNKeelMzVp5xhX19G8QXmrlrE_SRIeE',
    appId: '1:324268770895:ios:6eb8b6a1b7899bcaddcc3a',
    messagingSenderId: '324268770895',
    projectId: 'learning-67401',
    storageBucket: 'learning-67401.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmnNKeelMzVp5xhX19G8QXmrlrE_SRIeE',
    appId: '1:324268770895:ios:6eb8b6a1b7899bcaddcc3a',
    messagingSenderId: '324268770895',
    projectId: 'learning-67401',
    storageBucket: 'learning-67401.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1bPxT-A_y9c8UWEUeM2_3KpC5oB_yccY',
    appId: '1:324268770895:web:057c846e8c85f529ddcc3a',
    messagingSenderId: '324268770895',
    projectId: 'learning-67401',
    authDomain: 'learning-67401.firebaseapp.com',
    storageBucket: 'learning-67401.firebasestorage.app',
    measurementId: 'G-06VW8CTGDD',
  );
}
